# Generated by Django 4.2.3 on 2023-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionModel',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='game_atlas_id',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='house_rules',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
