# Generated by Django 4.2.3 on 2023-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_delete_collectionmodel_remove_gamemodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
