# Generated by Django 4.2.3 on 2023-07-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_remove_gamemodel_image_remove_gamemodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='image_url',
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='title',
            field=models.TextField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
